# Generated by Django 5.0.1 on 2024-02-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programapp', '0002_program_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Образовательаня программа', 'verbose_name_plural': 'Образовательные программы'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название ОП'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='programapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programapp.program', verbose_name='ОП'),
        ),
    ]
