# Generated by Django 5.0.2 on 2024-02-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programapp', '0003_alter_program_options_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
