# Generated by Django 5.0.2 on 2024-03-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programapp', '0005_ege_programege'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
