# Generated by Django 5.0.1 on 2024-02-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programapp', '0002_program_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program', models.ManyToManyField(to='programapp.program')),
                ('speciality', models.ManyToManyField(to='programapp.speciality')),
            ],
        ),
    ]
