# Generated by Django 5.0.1 on 2024-02-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
        ('programapp', '0003_alter_program_options_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='known_area',
            field=models.CharField(blank=True, choices=[('FZ', 'Физика'), ('MT', 'Математика'), ('IT', 'Информационные технологии')], default='FZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(to='programapp.program', verbose_name='Образовательные программы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='speciality',
            field=models.ManyToManyField(to='programapp.speciality', verbose_name='Специальности'),
        ),
    ]
