# Generated by Django 5.0.1 on 2024-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_course_known_area_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prof_typ',
            field=models.CharField(blank=True, choices=[('B', 'Базова'), ('P', 'Профизионнальная'), ('V', 'По выбору')], default='B', max_length=1),
        ),
    ]
