# Generated by Django 5.0.2 on 2024-02-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_foo_course_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
