# Generated by Django 5.0.2 on 2024-02-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_remove_course_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_load',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
