# Generated by Django 5.0.2 on 2024-03-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0007_course_study_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
