# Generated by Django 5.0.2 on 2024-03-30 03:49

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
    ]
