# Generated by Django 5.0.2 on 2024-03-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0010_historicalcourse'),
        ('programapp', '0006_speciality_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(blank=True, to='programapp.program', verbose_name='Образовательные программы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='speciality',
            field=models.ManyToManyField(blank=True, to='programapp.speciality', verbose_name='Специальности'),
        ),
    ]
